version: '3.8'

services:
  php-apache:
    image: php:8.2-apache
    container_name: Primer_contenedor
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    restart: always

    


